#!/bin/bash

function delete_empty_files () {

    # Deleting empty files in dumps
    find /root/vmwatcher/dumps/ -type f -size 0 -delete
    echo ""
    echo "Exiting $0"
    exit 0
}

# To catch ctrl+c
trap 'delete_empty_files' INT

# Default arguments
prevent=0
vm='one-1279'

# Parsing arguments
while [[ $# != 0 ]] 
do 
    case $1 in 
    -p | --prevent | -prevent ) 
        prevent=1
        ;;
    one*)
        vm="$1"
        ;;
    *)
        echo "invalid argument"
        ;;
    esac
    shift 
done

# unmounting /mnt if it exists
if [[ -f /mnt/mem ]]
then
    umount /mnt
fi

vmifs name $vm /mnt 

old_wd=$(pwd)

# Redirecting stdout to stderror 
cd /root/libvmtrace/build && make 1>&2 

# Run if make builds without any errors
if [[ $? == 0 ]]
then
    echo "Started monitoring." 1>&2
    bin/csec $vm $prevent 
else
    echo "Make failed." 1>&2
fi

cd $old_wd
